In [1]:
import numpy as np

In [2]:
# convert python list
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
myarray = np.array(mylist)

In [5]:
type(myarray)

numpy.ndarray

In [6]:
myarray

array([1, 2, 3])

In [8]:
myarray.shape
#1 row , 3 column

(3,)

In [9]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
type(mymatrix)

list

In [11]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
#convert to numpy matrix/array
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
type(mymatrix)

list

In [16]:
np.array(mymatrix).ndim

2

In [19]:
np.array(mymatrix).shape
# it is 3x3 matrix

(3, 3)

In [21]:
np.arange(0,10,2)
# strt from 0 and end on 10 with step size of 2

array([0, 2, 4, 6, 8])

In [22]:
np.arange(0,25,5)
#strt from 0 and end on 10 with step size of 2

array([ 0,  5, 10, 15, 20])

In [24]:
np.zeros(5)
# 0. means its float

array([0., 0., 0., 0., 0.])

In [25]:
# 2 dims matrix - 2 rows and 5 columns
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.zeros((2,5)).ndim

2

In [27]:
np.zeros((2,5)).shape

(2, 5)

In [28]:
np.zeros(5).shape

(5,)

In [29]:
np.zeros(5).ndim

1

In [30]:
# 4x4 matrix of 1's
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.ones((4,4)).shape

(4, 4)

In [35]:
np.ones((4,4)).ndim

2

In [36]:
np.linspace(0,10,1)
# (start point , stop point , number of data points between start and stop)

array([0.])

In [37]:
np.linspace(0,10,2)

array([ 0., 10.])

In [38]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [39]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [41]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [42]:
len(np.linspace(0,10,1))

1

In [43]:
len(np.linspace(0,10,11))

11

In [44]:
np.eye(4)
# identity matrix is square matrix ALWAYS

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.random.rand(1)
#Create an array of the given shape and populate it with
#random samples from a uniform distribution
#over ``[0, 1)``.

array([0.26853203])

In [46]:
np.random.rand(1)
# it means that it should give a random number betwenn 0 and 1

array([0.27163654])

In [48]:
np.random.rand(2,3)
# this gives random nos betweeen 2 rows and 3 columns

array([[0.933856  , 0.51764858, 0.35214938],
       [0.19900271, 0.34748699, 0.11053932]])

In [49]:
np.random.rand(2,3)

array([[0.43757615, 0.56273741, 0.60300839],
       [0.53642171, 0.7212345 , 0.28807262]])

In [50]:
np.random.rand(2,3)

array([[0.74815543, 0.7872549 , 0.29363698],
       [0.48549586, 0.12188905, 0.73962686]])

In [51]:
np.random.rand(3,2)

array([[0.31969909, 0.32154416],
       [0.45386316, 0.4229137 ],
       [0.07379954, 0.0903864 ]])

In [52]:
np.random.rand(3,2).shape

(3, 2)

In [53]:
np.random.rand(3,2).ndim

2

In [54]:
np.random.rand(3,3)

array([[0.53556012, 0.31683717, 0.2421489 ],
       [0.40235347, 0.71272519, 0.29751374],
       [0.20738963, 0.23490599, 0.83488289]])

In [55]:
np.random.rand(3,3).shape

(3, 3)

In [57]:
np.random.rand(3,3).ndim

2

In [59]:
np.random.randn(1)
#randn is for standard normal distribution

array([0.68223551])

In [60]:
np.random.randint(0,10,10)# returns random integers
# betwen 0 and 10 give me 10 random integers
# NO FLOATS please!!!

array([1, 1, 7, 9, 5, 9, 4, 8, 0, 8])

In [61]:
# setting random seed
np.random.seed(42) # hahah life's answer :-)
np.random.rand(5)


array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [62]:
# now call again
np.random.rand(5)

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [64]:
np.random.seed(42) # hahah life's answer :-)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

so cell #61 and #64 give same random nos.

### Method calls for np arrays

In [65]:
arr = np.arange(0,25)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
# but 5,4 is not right as 5x4 = 20 and we need to fit 5x5 = 25 elemnts

In [69]:
random_arr = np.random.randint(0,20,10)

In [70]:
random_arr

array([18, 10, 10,  3,  7,  2,  1, 11,  5,  1])

In [71]:
random_arr.max

<function ndarray.max>

In [72]:
random_arr.max()

18

In [73]:
random_arr.min()

1

In [74]:
random_arr.argmin() # argmin gives position of minimum element

6

In [75]:
random_arr.shape

(10,)

In [77]:
rarr = random_arr.reshape(5,5)

ValueError: cannot reshape array of size 10 into shape (5,5)

In [80]:
rarr = random_arr.reshape(10,1)
# so 10x1 worked becauase it needs to fit in 10 elements
# 1 rows

In [81]:
rarr.shape

(10, 1)

In [82]:
random_arr.shape

(10,)

In [84]:
rarr # gives one column after reshaping

array([[18],
       [10],
       [10],
       [ 3],
       [ 7],
       [ 2],
       [ 1],
       [11],
       [ 5],
       [ 1]])

In [85]:
rarr = random_arr.reshape(1,10) # 1 row and 10 columns

In [86]:
rarr

array([[18, 10, 10,  3,  7,  2,  1, 11,  5,  1]])

In [87]:
rarr.shape

(1, 10)

In [88]:
rarr.ndim

2

In [89]:
myarray = np.arange(0,10,101)

In [91]:
myarray

array([0])

### Indexing , grabbing slices , Broadcasting,conditional selection

In [92]:
myarray = np.arange(0,10)

In [93]:
myarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
myarray = np.arange(0,10,9)

In [97]:
myarray

array([0, 9])

In [98]:
myarray = np.arange(0,10)

In [99]:
myarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
myarray[:5]

array([0, 1, 2, 3, 4])

In [101]:
myarray[5:]

array([5, 6, 7, 8, 9])

In [102]:
myarray[1:6]

array([1, 2, 3, 4, 5])

In [103]:
myarray[::] # gives all elements

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Broadcasting


In [105]:
myarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
myarray[:5] = 100 # make 5 elements in myarray = 100
# broadcasting 100 to myarray

In [107]:
myarray

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [111]:
myarray = np.arange(0,10)# original
myarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
slice_of_myarray = myarray[:5]
slice_of_myarray

array([0, 1, 2, 3, 4])

In [113]:
slice_of_myarray[:5] = 500

In [114]:
slice_of_myarray

array([500, 500, 500, 500, 500])

In [115]:
# now see the original myarray again
myarray

# this includes the slice_of_myarray values also.

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

### Indexing on arrays and matrix

In [117]:
arr_2d = np.array([[1,2,3],[3,4,5],[5,6,7]])
arr_2d

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [118]:
arr_2d.shape

(3, 3)

In [119]:
arr_2d[0]

array([1, 2, 3])

In [120]:
arr_2d[-1]

array([5, 6, 7])

In [121]:
arr_2d[2]

array([5, 6, 7])

In [122]:
arr_2d[1][1]

4

In [123]:
arr_2d[1,1] 
# same as cell#122

4

In [124]:
arr_2d[:2] # gives only 2 rows

array([[1, 2, 3],
       [3, 4, 5]])

In [126]:
arr_2d[:] # gives all rows

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [128]:
arr_2d[:2,1:]
# start from 2nd row and for 1st column grab all elements 
# starting from 1

array([[2, 3],
       [4, 5]])

### Conditional selection ( MOST common type used)

In [130]:
arr = np.arange(1,11)

In [131]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
# check for conditions

arr > 5
# check where in array element is greater than 5 nd
# give true wherever applicable i.e greater than 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [134]:
arr == 5

array([False, False, False, False,  True, False, False, False, False,
       False])

In [135]:
arr !=0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [136]:
arr !=9

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True])

In [137]:
# in practice

arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [138]:
arr[arr < 4]

array([1, 2, 3])

In [139]:
arr[arr==5] # 5 is present

array([5])

In [140]:
arr[arr!=8] # 8 is gone

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])

In [143]:
dice_rolls = np.arange(1,6)

In [144]:
dice_rolls

array([1, 2, 3, 4, 5])

In [145]:
total_rolls_over_two = dice_rolls > 2
total_rolls_over_two

array([False, False,  True,  True,  True])

## Mathematical operations with numpy

In [146]:
arr = np.arange(0,10)

In [147]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
arr + 5 # add 5 to every element

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [150]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [151]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [152]:
# arr + arr == ar*2

In [153]:
arr / arr

<ipython-input-153-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [154]:
# nan = 0/0 ; numpy replacses nan with 0/0

In [155]:
arr.sum()

45

In [156]:
arr.mean()

4.5

In [157]:
arr.max()

9

In [159]:
arr.std() # standard deviation

2.8722813232690143

In [160]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [161]:
arr2d.sum()

300

In [162]:
arr2d.sum(axis=0) #means 1st column for all the rows
# means sum accross rows

array([50, 55, 60, 65, 70])

In [163]:
arr2d.sum(axis=1) # means sum accross columns

array([ 10,  35,  60,  85, 110])